"""The cross-repository conformance contract, checked from bytes rather than imports.

`tests/fixtures/portfolio_artifact_envelope_v1.json` holds the exact bytes of the
canonical envelope produced by `driving-risk-metrics`. They were copied in, not
imported: this repository must never depend on driving-risk-metrics at runtime,
and a shared package would turn three independent implementations into one
implementation with three call sites, which proves nothing.

If a future change to the envelope specification breaks these tests, the fix is to
change all three repositories and recopy the fixture, not to relax the test.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import pytest

FIXTURE = Path(__file__).resolve().parents[1] / "fixtures" / "portfolio_artifact_envelope_v1.json"


def test_this_repository_does_not_import_the_p1_package_anywhere() -> None:
    """Runtime coupling to driving-risk-metrics would make this conformance check circular."""

    source_root = Path(__file__).resolve().parents[2] / "src"
    offenders = [
        path.relative_to(source_root).as_posix()
        for path in source_root.rglob("*.py")
        if "drivemetrics" in path.read_text(encoding="utf-8")
    ]

    assert offenders == []


def test_an_artifact_produced_by_p1_is_accepted_here_unchanged() -> None:
    """The point of the envelope: driving-risk-metrics writes it, the other two read it."""

    from bevcalib.artifacts.envelope import PortfolioArtifactEnvelopeV1, canonical_json_bytes

    # Canonical bytes exclude the trailing newline that makes the fixture a text file.
    canonical = FIXTURE.read_bytes().removesuffix(b"\n")

    envelope = PortfolioArtifactEnvelopeV1.model_validate_json(canonical)

    assert envelope.producer_repository == "driving-risk-metrics"
    assert envelope.schema_version == "portfolio-artifact-envelope/v1"
    assert canonical_json_bytes(envelope.model_dump()) == canonical


def test_every_portfolio_repository_is_an_accepted_producer() -> None:
    """perception-error-to-aeb consumes this repository's artifacts, so all three are named."""

    from bevcalib.artifacts.envelope import PortfolioArtifactEnvelopeV1

    document = json.loads(FIXTURE.read_text(encoding="utf-8"))

    for repository in ("driving-risk-metrics", "bev-calibration-lab", "perception-error-to-aeb"):
        candidate = document | {"producer_repository": repository}
        envelope = PortfolioArtifactEnvelopeV1.model_validate(candidate)
        assert envelope.producer_repository == repository

    with pytest.raises(
        ValueError,
        match=r"^1 validation error for PortfolioArtifactEnvelopeV1\nproducer_repository\n  Input should be 'driving-risk-metrics', 'bev-calibration-lab' or 'perception-error-to-aeb'",
    ):
        PortfolioArtifactEnvelopeV1.model_validate(
            document | {"producer_repository": "some-unrelated-project"}
        )


def test_this_repository_can_produce_an_envelope_p1_would_also_accept() -> None:
    """Conformance has to hold in both directions or the contract is one-way."""

    from bevcalib.artifacts.envelope import PortfolioArtifactEnvelopeV1, canonical_json_bytes

    payload = {"fixture": "synthetic", "values": [0, 1]}
    document = {
        "schema_version": "portfolio-artifact-envelope/v1",
        "producer_repository": "bev-calibration-lab",
        "producer_release": "v0.0.0",
        "producer_commit": "a" * 40,
        "artifact_type": "bev-calibration-result-set/v1",
        "protocol_hash": "b" * 64,
        "dataset_manifest_hash": "c" * 64,
        "created_at_utc": "2026-09-02T00:00:00Z",
        "payload_sha256": hashlib.sha256(canonical_json_bytes(payload)).hexdigest(),
        "payload": payload,
    }

    envelope = PortfolioArtifactEnvelopeV1.model_validate(document)
    serialized = canonical_json_bytes(envelope.model_dump())

    # Re-reading our own output is the half of the round trip a producer controls.
    assert PortfolioArtifactEnvelopeV1.model_validate_json(serialized) == envelope
    # And the payload digest is the half a consumer will independently recompute.
    assert (
        hashlib.sha256(canonical_json_bytes(json.loads(serialized)["payload"])).hexdigest()
        == document["payload_sha256"]
    )


def test_the_checked_in_schemas_match_the_models_they_document(tmp_path: Path) -> None:
    """A schema regenerated by hand drifts; one regenerated by command cannot."""

    from bevcalib.artifacts.schemas import contract_schema_documents

    schema_directory = Path(__file__).resolve().parents[2] / "schemas"

    for filename, document in contract_schema_documents().items():
        assert (schema_directory / filename).read_bytes() == document


def test_regenerating_the_schemas_writes_exactly_the_committed_documents(tmp_path: Path) -> None:
    """Regeneration is the only supported way to change a schema, so it must be exact."""

    from bevcalib.artifacts.schemas import contract_schema_documents, write_contract_schemas

    written = write_contract_schemas(tmp_path)

    assert {path.name for path in written} == set(contract_schema_documents())
    for path in written:
        assert path.read_bytes() == contract_schema_documents()[path.name]
